comandoAbrir = ["abrir", "abre", "iniciar", "executar", "inicializa", "executa", "inicia"]
comandoFinalizar = ["finalizar", "até mais tarde", "até depois", "tchau", "até"]
sitesNavegador = ["google", "instagram", "youtube", "canva", "microsoft"]
comandoNegar = ["não", "nada", "somente", "apenas"]
comandoAceitar = ["sim", "quero", "claro", "por favor"]
comandoExplorador = ["explorador", "arquivos", "pastas"]
comandoNotas = ["notas", "notepad", "bloco de notas"]
comandoMusica = ["aplciativo de músicas", "escutar música", "app de músicas", "som"]